import Link from "next/link";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { FileIcon, StarIcon } from "lucide-react";
import { SideNav } from "./side-nav";
import { Header } from "../header";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DasboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Header />
    <main className="container mx-auto pt-12">

      <div className="flex gap-8">
        <SideNav />

        <div className="w-full">
          {children}
        </div>

        
      </div>
    </main>
    </>
  );
}